name: Build Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build Release Version
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.20"]
        os: [linux, windows, darwin]
        arch: [amd64, arm64] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set env variables
      run: |
        echo "OUTPUT_DIR=${OUTPUT_DIR}" >> $GITHUB_ENV
        echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV

    - name: Create the output directory
      run: mkdir ${{ env.OUTPUT_DIR }}

    - name: Build
      working-directory: ./cmd
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}_${{ matrix.os }}_${{ matrix.arch }}
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.APP_NAME }}/${{ env.OUTPUT_DIR }}_${{ matrix.os }}_${{ matrix.arch }}
