name: Build Release

on:
  push: 
    branches:
      - main

# Add this to avoid 403 error
permissions:
  contents: write

jobs:
  build:
    name: Build Release Version
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.20"]
        os: [linux, windows, darwin]
        arch: [amd64, arm64] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set env variables
      # change version every time you create a release
      run: |
        echo "APP_NAME=maven_ci_tool" >> $GITHUB_ENV
        echo "VERSION=v0.1.2" >> $GITHUB_ENV

    - name: Build
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ${{ env.APP_NAME }}_${{ matrix.os }}_${{ matrix.arch }} ./cmd
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        files: ${{ env.APP_NAME }}_${{ matrix.os }}_${{ matrix.arch }}
