name: Build Release

on:
  push: 
    branches:
      - main

jobs:
  build:
    name: Build Release Version
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.20"]
        os: [linux, windows, darwin]
        arch: [amd64, arm64] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set env variables
      # change version every time you create a release
      run: |
        echo "OUTPUT_DIR=./out" >> $GITHUB_ENV
        echo "APP_NAME=maven_ci_tool" >> $GITHUB_ENV
        echo "VERSION=v0.1.0" >> $GITHUB_ENV

    - name: Create the output directory
      run: mkdir ${{ env.OUTPUT_DIR }}

    - name: Build
      working-directory: ./cmd
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ${{ env.OUTPUT_DIR }}/${{ env.APP_NAME }}_${{ matrix.os }}_${{ matrix.arch }}
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        files: ${{ env.APP_NAME }}/${{ env.OUTPUT_DIR }}_${{ matrix.os }}_${{ matrix.arch }}
